--- #YAML:1.0
name:               Crypt-GCrypt
version:            1.25
abstract:           Perl interface to the GNU libgcrypt library
author:
    - Alessandro Ranellucci <aar@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  git://github.com/alexrj/Crypt-GCrypt.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
